language: python
cache: pip

python:
  - 2.7
  - 3.3
  - 3.4
  - 3.5
  - pypy
  - pypy3

matrix:
  include:
    - language: generic
      python: 2.7
      os: osx
    - language: generic
      python: 3.3
      os: osx
    - language: generic
      python: 3.5
      os: osx
  allow_failures:
    - python: pypy3

install:
  - |
      if [ "$TRAVIS_PYTHON_VERSION" = "pypy" ]; then
        export PYENV_ROOT="$HOME/.pyenv"
        if [ -f "$PYENV_ROOT/bin/pyenv" ]; then
          pushd "$PYENV_ROOT" && git pull && popd
        else
          rm -rf "$PYENV_ROOT" && git clone --depth 1 https://github.com/yyuu/pyenv.git "$PYENV_ROOT"
        fi
        export PYPY_VERSION="5.4.1"
        "$PYENV_ROOT/bin/pyenv" install --skip-existing "pypy-$PYPY_VERSION"
        virtualenv --python="$PYENV_ROOT/versions/pypy-$PYPY_VERSION/bin/python" "$HOME/virtualenvs/pypy-$PYPY_VERSION"
        source "$HOME/virtualenvs/pypy-$PYPY_VERSION/bin/activate"
      fi
  - if [[ $TRAVIS_OS_NAME == osx ]]; then brew install openssl; fi
  - if [[ $TRAVIS_OS_NAME == osx ]]; then export LDFLAGS="-L$(brew --prefix openssl)/lib" CFLAGS="-I$(brew --prefix openssl)/include"; fi
  - virtualenv --python=python env
  - source env/bin/activate
  - pip install coverage flake8 wheel
  - python setup.py bdist_wheel
  - pip install dist/*.whl

script:
  - source env/bin/activate
  - flake8 signxml
  - coverage run --source=signxml ./test/test.py
# - coverage report --show-missing

after_success:
  - bash <(curl -s https://codecov.io/bash)

sudo: false
